import { CalendarDays, Download, Sparkles, TrendingDown, TrendingUp } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AiPanel, PageHeading } from "../components/Ui";
import { useAuth } from "../context/AuthContext";
import { useFinance } from "../context/FinanceContext";
import { formatCurrency } from "../lib/format";

export function ReportsPage() {
  const { user } = useAuth();
  const { monthly, categoryReport, insights, exportCsv } = useFinance();
  const currency = user?.currency || "LKR";
  const topCategory = categoryReport[0];
  const average = monthly?.trend.length ? monthly.trend.reduce((sum, item) => sum + item.expenses, 0) / monthly.trend.length : 0;

  return (
    <>
      <PageHeading eyebrow="Patterns over noise" title="Reports & trends" copy="Step back from individual purchases and see the decisions they add up to." action={<div className="heading-actions"><button className="month-selector"><CalendarDays size={17} />Last 6 months</button><button className="button secondary" onClick={() => void exportCsv()}><Download size={17} />Export</button></div>} />
      <section className="report-summary-grid"><article className="card report-stat"><span className="report-stat-icon positive"><TrendingUp /></span><div><span>Average monthly income</span><strong>{formatCurrency((monthly?.trend.reduce((sum, item) => sum + item.income, 0) || 0) / (monthly?.trend.length || 1), currency)}</strong><small>Stable across the period</small></div></article><article className="card report-stat"><span className="report-stat-icon warning"><TrendingDown /></span><div><span>Average monthly spend</span><strong>{formatCurrency(average, currency)}</strong><small>{monthly && monthly.expenses < average ? "Below your six-month average" : "Above your six-month average"}</small></div></article><article className="card report-stat"><span className="report-stat-icon neutral"><Sparkles /></span><div><span>Top spend category</span><strong>{topCategory?.name || "No spending yet"}</strong><small>{topCategory ? formatCurrency(topCategory.amount, currency) : "Add transactions to compare"}</small></div></article></section>
      <div className="reports-grid"><section className="card report-chart span-two"><div className="card-heading"><div><span className="eyebrow">Monthly comparison</span><h2>Income vs. expenses</h2></div></div><div className="bar-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={monthly?.trend || []} barGap={5}><CartesianGrid vertical={false} stroke="#e9eeeb" /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: "#71807a", fontSize: 12 }} /><YAxis axisLine={false} tickLine={false} tickFormatter={(value) => `${value / 1000}k`} tick={{ fill: "#71807a", fontSize: 12 }} /><Tooltip formatter={(value) => formatCurrency(Number(value), currency)} cursor={{ fill: "#f3f6f4" }} contentStyle={{ border: 0, borderRadius: 14, boxShadow: "0 12px 30px rgba(19,45,42,.12)" }} /><Bar dataKey="income" fill="#4cae95" radius={[7, 7, 0, 0]} maxBarSize={24} /><Bar dataKey="expenses" fill="#e18a77" radius={[7, 7, 0, 0]} maxBarSize={24} /></BarChart></ResponsiveContainer></div></section><section className="card category-breakdown"><div className="card-heading"><div><span className="eyebrow">This month</span><h2>Spending mix</h2></div></div><div className="donut-chart"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={categoryReport} dataKey="amount" innerRadius={64} outerRadius={91} paddingAngle={3} stroke="none">{categoryReport.map((item) => <Cell key={item.categoryId} fill={item.color} />)}</Pie><Tooltip formatter={(value) => formatCurrency(Number(value), currency)} contentStyle={{ border: 0, borderRadius: 12 }} /></PieChart></ResponsiveContainer><div className="donut-center"><strong>{formatCurrency(monthly?.expenses || 0, currency, true)}</strong><span>total spent</span></div></div><div className="category-legend">{categoryReport.slice(0, 5).map((item) => <div key={item.categoryId}><span><i style={{ background: item.color }} />{item.name}</span><strong>{monthly?.expenses ? Math.round((item.amount / monthly.expenses) * 100) : 0}%</strong></div>)}</div></section><AiPanel report={insights} currency={currency} /><section className="card savings-card span-two"><div><span className="eyebrow">Progress that compounds</span><h2>Your average savings gap is {formatCurrency((monthly?.trend.reduce((sum, item) => sum + item.income - item.expenses, 0) || 0) / (monthly?.trend.length || 1), currency)} per month.</h2><p>Holding this pace for a year would create a meaningful cushion without requiring a dramatic lifestyle change.</p></div><div className="savings-visual"><span>12-month potential</span><strong>{formatCurrency(((monthly?.trend.reduce((sum, item) => sum + item.income - item.expenses, 0) || 0) / (monthly?.trend.length || 1)) * 12, currency)}</strong></div></section></div>
    </>
  );
}

